/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;

import servernio.EchoServer;
import servernio.NioClient;

/**
 *
 * @author Axel
 */
public class ParamsServer extends javax.swing.JFrame {

    /**
     * Creates new form ParamsServer
     */
    public ParamsServer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        titre = new javax.swing.JLabel();
        createServer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ipAddress = new javax.swing.JTextField();
        join = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tetris Setup Server");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(600, 250));
        setResizable(false);
        getContentPane().setLayout(null);

        titre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titre.setForeground(new java.awt.Color(240, 240, 240));
        titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titre.setText("Tetris Online");
        getContentPane().add(titre);
        titre.setBounds(10, 11, 590, 29);

        createServer.setText("Create Local Server");
        createServer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createServerMouseClicked(evt);
            }
        });
        getContentPane().add(createServer);
        createServer.setBounds(10, 70, 225, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Create Server");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 40, 169, 22);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Join Server");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 120, 152, 22);

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("IP Address:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 160, 110, 14);
        getContentPane().add(ipAddress);
        ipAddress.setBounds(130, 160, 159, 20);

        join.setText("Join");
        join.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                joinMouseClicked(evt);
            }
        });
        getContentPane().add(join);
        join.setBounds(330, 160, 88, 23);

        error.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        error.setForeground(new java.awt.Color(255, 0, 0));
        error.setText("IP Address Empty");
        error.setVisible(false);
        getContentPane().add(error);
        error.setBounds(440, 160, 141, 14);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tetris_Server.png"))); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(600, 337));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 600, 250);

        pack();
    }// </editor-fold>                        

    private void createServerMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
    	this.setVisible(false);
    	
    	new Thread(){
    		public void run() {
    			EchoServer.main();
    		}
    	}.start();		
		
    	int i = 0;
    	while(i < 1000){
    		System.out.println(i++);
    	}
    	
    	new Thread(){
    		public void run() {
    			NioClient.main("localhost");
    		}
    	}.start();
    	
    }                                         

    private void joinMouseClicked(java.awt.event.MouseEvent evt) {                                  
        // TODO add your handling code here:
        System.out.println(ipAddress.getText());
        if(!ipAddress.getText().isEmpty()){
        	
        	new Thread(){
        		public void run() {
        			NioClient.main(ipAddress.getText());
        		}
        	}.start();
        	this.setVisible(false);
        }else{
            error.setVisible(true);
        }
    }                                                                 

    // Variables declaration - do not modify                     
    private javax.swing.JButton createServer;
    private javax.swing.JLabel error;
    private javax.swing.JTextField ipAddress;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton join;
    private javax.swing.JLabel titre;
    // End of variables declaration                   
}
