/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import servernio.NioClient;

/**
 *
 * @author Axel
 */
public class ParamsServer extends javax.swing.JFrame {

    private static Object lock;
	/**
     * Creates new form ParamsServer
	 * @param lock2 
     */
    public ParamsServer() {
        initComponents();
        this.lock = lock;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        titre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ipAddress = new javax.swing.JTextField();
        join = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tetris Setup Server");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(400, 250));
        setResizable(false);
        getContentPane().setLayout(null);

        titre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titre.setForeground(new java.awt.Color(240, 240, 240));
        titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titre.setText("Tetris Online");
        getContentPane().add(titre);
        titre.setBounds(-40, 10, 480, 29);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Join Server");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 40, 152, 22);

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("IP Address:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 110, 14);
        getContentPane().add(ipAddress);
        ipAddress.setBounds(130, 60, 159, 30);

        join.setText("Join");
        join.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                joinMouseClicked(evt);
            }
        });
        join.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinActionPerformed(evt);
            }
        });
        getContentPane().add(join);
        join.setBounds(10, 100, 88, 23);

        error.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        error.setForeground(new java.awt.Color(255, 0, 0));
        error.setText("IP Address Empty");
        error.setVisible(false);
        getContentPane().add(error);
        error.setBounds(130, 110, 141, 14);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tetris_Server.png"))); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(600, 200));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -20, 600, 260);

        pack();
    }// </editor-fold>                        

    private void joinMouseClicked(java.awt.event.MouseEvent evt) {                                  
        // TODO add your handling code here:
        System.out.println(ipAddress.getText());
        if(!ipAddress.getText().isEmpty()){

        	new Thread(){
        		
				public void run() {
        			NioClient.main(ipAddress.getText());
        		}
        	}.start();
        	this.dispose();
        }else{
            error.setVisible(true);
            System.out.println("vide");
        }
    }                                 

    private void joinActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParamsServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParamsServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParamsServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParamsServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParamsServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel error;
    private javax.swing.JTextField ipAddress;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton join;
    private javax.swing.JLabel titre;
    // End of variables declaration                   
}
